### ISSUE TITLE
报错：程序名错误

### ISSUE THREAD

**Issue by BevisShao** [ykisme/LayoutInspector#3]
PS E:\InstallLocation\Github-Desk\clone\LayoutInspector\jar> java -jar .\LayoutInspector.jar D:\AS\SDK\platform-tools\adb.exe com.android.systemui
命令参数为adb全路径 程序名，比如: /bin/adb com.android.systemui
wait for device
x150-0123456789ABCDEF
程序名错误
PS E:\InstallLocation\Github-Desk\clone\LayoutInspector\jar>
-------------------------------------------
是不是我的真机没被root的原因?(win10 powershell)

**Comment by ykisme** [comment]
嗯，是的，包必须是可调试的，com.android.systemui通常是不能的呦，除非你刷的是debug版的bin或者root了也可以。

**Comment by BevisShao** [comment]
谢谢。真机是n年的老机器了，对应的源码也没了，bin或者重新编译debug版本是没法实现的，只能找root工具试试。
